FROM ubuntu:14.04

RUN apt-get update
RUN apt-get install -y git cmake build-essential libeigen3-dev

# gtest
WORKDIR /root/
RUN git clone https://github.com/google/googletest.git
WORKDIR googletest
RUN mkdir build
WORKDIR build
RUN cmake -DCMAKE_BUILD_TYPE=Release ..
RUN make
RUN make install

# google benchmark
WORKDIR /root/
RUN git clone https://github.com/google/benchmark.git
WORKDIR benchmark
RUN mkdir build
WORKDIR build
RUN cmake -DCMAKE_BUILD_TYPE=Release ..
RUN make
RUN make install

# orocos kdl
WORKDIR /root/
RUN git clone https://github.com/orocos/orocos_kinematics_dynamics.git
WORKDIR orocos_kinematics_dynamics/orocos_kdl/
RUN mkdir build
WORKDIR build
RUN cmake -DCMAKE_C_FLAGS="-Ofast" -DCMAKE_BUILD_TYPE=Release ..
RUN make
RUN make install

# pkl
WORKDIR /root/
COPY . .

WORKDIR /root/pkl
RUN cmake -DCMAKE_BUILD_TYPE=Release .
RUN make
RUN make install

WORKDIR /root/benchmark/kdl
RUN cmake -DCMAKE_BUILD_TYPE=Release .
RUN make

WORKDIR /root/pkl/tests
RUN cmake -DCMAKE_BUILD_TYPE=Release .
RUN make
